import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { LoadingPage, LoadingSpinner } from "./components/loading";
import { RouterOutputs, api } from "~/utils/api";
import React from "react";
import toast from "react-hot-toast";
import Image from "next/image";

const CreateSongWizard = () => {
  const { user } = useUser();
  const [title, setTitle] = React.useState("");
  const [artist, setArtist] = React.useState("");
  const [key, setKey] = React.useState("");

  if (!user) {
    return null;
  }

  const ctx = api.useContext();
  const { mutate, isLoading: isPosting } = api.song.create.useMutation({
    onSuccess: () => {
      setTitle("");
      setArtist("");
      setKey("");
      void ctx.song.getAll.invalidate();
    },
    onError: () => {
      toast.error("Failed to create song");
    },
  });

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.imageUrl}
        alt="profile image"
        className="h-14 w-14 rounded-full"
      />
      <input
        type="text"
        placeholder="Song Title"
        className="bg-transparent outline-none"
        onChange={(e) => setTitle(e.target.value)}
        value={title}
        disabled={isPosting}
      />
      <input
        type="text"
        placeholder="Artist Name"
        className="bg-transparent outline-none"
        onChange={(e) => setArtist(e.target.value)}
        value={artist}
        disabled={isPosting}
      />

      <label>Choose a Key:</label>
      <select id="Song Key" onChange={(e) => setKey(e.target.value)}>
        <option value="C">C</option>
        <option value="C#">C#</option>
        <option value="Db">Db</option>
        <option value="D">D</option>
        <option value="D#">D#</option>
        <option value="Eb">Eb</option>
        <option value="E">E</option>
        <option value="F">F</option>
        <option value="F#">F#</option>
        <option value="Gb">Gb</option>
        <option value="G">G</option>
        <option value="G#">G#</option>
        <option value="Ab">Ab</option>
        <option value="A">A</option>
        <option value="A#">A#</option>
        <option value="Bb">Bb</option>
        <option value="B">B</option>
      </select>
      <input type="radio" name="Mode" />
      <label>Major</label>
      <br />
      <input type="radio" name="Mode" />
      <label>Minor</label>
      <br />

      {title && artist && key !== "" && !isPosting && (
        <button
          onClick={() =>
            mutate({
              title: title,
              artist: artist,
              key: key,
            })
          }
          disabled={isPosting}
        >
          Post
        </button>
      )}
      {isPosting && (
        <div>
          <LoadingSpinner />
        </div>
      )}
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: songsLoading } = api.song.getAll.useQuery();

  if (songsLoading) {
    return <LoadingPage />;
  }

  if (!data) {
    return <div>Something went wrong</div>;
  }

  return (
    <div>
      {data?.map((fullPost) => (
        <SongView {...fullPost} key={fullPost?.song.id} />
      ))}
    </div>
  );
};

type SongWithUser = RouterOutputs["song"]["getAll"][number];
const SongView = (props: SongWithUser) => {
  const { song } = props;

  return <div key={song.id}>{song.title}</div>;
};
export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  api.song.getAll.useQuery();
  if (!userLoaded) return <div />;
  return (
    <>
      <Head>
        <title>Which Song? What Song?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://m.media-amazon.com/images/I/41yr3UuyZhL.__AC_SX300_SY300_QL70_FMwebp_.jpg"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {isSignedIn && (
            <div className="flex justify-center">
              <CreateSongWizard />
              <SignOutButton />
            </div>
          )}
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Time <span className="text-[hsl(280,100%,70%)]">To</span> Jam
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Songs →</h3>
              <div className="text-lg">Songs</div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Play-Along →</h3>
              <div className="text-lg">Play-Along</div>
            </Link>
            <div>
              <Feed />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
