import Head from "next/head";
import Link from "next/link";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { RouterOutputs, api } from "~/utils/api";

const CreateSongWizard = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.imageUrl}
        alt="profile image"
        className="h-14 w-14 rounded-full"
      />
      <input
        type="text"
        placeholder="Song Title"
        className="bg-transparent outline-none"
      />
    </div>
  );
};

type SongWithUser = RouterOutputs["song"]["getAll"][number];
const SongView = (props: SongWithUser) => {
  const { song, user } = props;

  return <div key={song.id}>{song.title}</div>;
};
export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.song.getAll.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Something went wrong</div>;
  }

  return (
    <>
      <Head>
        <title>Which Song? What Song?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!user.isSignedIn && (
            <div className="flex justify-center">
              <SignInButton />
            </div>
          )}
          {user.isSignedIn && (
            <div className="flex justify-center">
              <CreateSongWizard />
            </div>
          )}
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Time <span className="text-[hsl(280,100%,70%)]">To</span> Jam
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Songs →</h3>
              <div className="text-lg">Songs</div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Play-Along →</h3>
              <div className="text-lg">Play-Along</div>
            </Link>
            <div>
              {[...data]?.map((fullPost) => (
                <SongView {...fullPost} key={fullPost.song.id} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
